export const POKEMON_REQUESTED = 'POKEMON_REQUESTED';
export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAIL = 'GET_POKEMON_FAIL';
export const SELECT_POKEMON = 'SELECT_POKEMON';
export const UNSELECT_POKEMON = 'UNSELECT_POKEMON';

